pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Srinu-rj/E-Commerce-application.git'     
      }
    }
    stage('Build') {
      steps {
        sh 'mvn clean package'
      }
    }
    stage('Unit Tests') {
      steps {
        sh 'mvn test'
        archiveArtifacts artifacts: 'target/*.jar'
      }
    }
  }
}
